name: myy
version: 0.34.5
synopsis: Lambda calculus interpreter
description: See README at <https://github.com/japiirainen/myy#readme>
maintainer: Joona Piirainen <joona.piirainen@gmail.com>
github: japiirainen/myy
category: Development
extra-source-files:
  - CHANGELOG.md

ghc-options: -Wall

dependencies:
  - base
  - parsec
  - megaparsec
  - mtl
  - template-haskell
  - ansi-wl-pprint
  - tasty
  - tasty-hunit
  - prettyprinter
  - transformers
  - haskeline
  - containers
  - pretty
  - text
  - repline

library:
  source-dirs: src
  exposed-modules:
    - Myy

executable:
  main: Main.hs
  source-dirs: app
  dependencies:
    - myy

tests:
  tasty:
    main: tests/Main.hs
    source-dirs: tasty
    dependencies:
      - base
      - parsec
      - megaparsec
      - mtl
      - template-haskell
      - ansi-wl-pprint
      - tasty
      - tasty-hunit
      - prettyprinter
      - transformers
      - haskeline
      - containers
      - pretty
      - text
      - repline

