name: myy
version: 0.34.5
synopsis: Lambda calculus interpreter
description: See README at <https://github.com/japiirainen/myy#readme>
maintainer: Joona Piirainen <joona.piirainen@gmail.com>
github: japiirainen/myy
category: Development
extra-source-files:
  - CHANGELOG.md

ghc-options: -Wall

dependencies:
  - base
  - parsec
  - megaparsec
  - mtl
  - template-haskell
  - ansi-wl-pprint
  - tasty
  - tasty-hunit
  - prettyprinter
  - transformers
  - haskeline
  - containers
  - pretty
  - text
  - repline
  - directory

library:
  source-dirs: src
  exposed-modules:
    - Myy
    - Myy.Lex
    - Myy.Exp
    - Myy.Globals
    - Myy.Monad
    - Myy.Pretty
    - Myy.Token
    - Myy.Type
    - Myy.Util
    - Myy.Parse
    - Myy.Statement
    - Myy.Unchecked
    - Myy.Check
    - Myy.Eval
    - Myy.Repl

executable:
  main: Main.hs
  source-dirs: app
  dependencies:
    - myy

tests:
  tasty:
    main: Main.hs
    source-dirs: tasty

    dependencies:
      - base
      - myy
      - parsec
      - megaparsec
      - mtl
      - template-haskell
      - ansi-wl-pprint
      - tasty
      - tasty-hunit
      - prettyprinter
      - transformers
      - haskeline
      - containers
      - pretty
      - text
      - repline

